driver:
  name: docker
  use_sudo: false # For Native Docker on Mac. Comment if using Toolbox (docker-machine)
  driver_config:
    ssl_verify_mode: ":verify_none"

provisioner:
  name: chef_zero

platforms:
  - name: amazonlinux
    driver_config:
      image: amazonlinux:latest
      platform: rhel

verifier:
  name: inspec

suites:
    - name: default
      run_list:
       - recipe[jenkin::default]
      attributes:
      jenkins:
       http_proxy:
        vairant: nginix
